package com.movilehack.redlight.tatuador;

public enum Style {
  OLD_SCHOOL, NEW_SCHOOL, ORIENTAL, TRIBAL, CELTA, PONTILHISMO, SUMI, ALTO_RELEVO, PSICODELICO, BOLD_LINE, TRADICIONAL, AQUARELA, GEOMETRICA, ESTILIZADA
}
